### Post new academic period
POST http://127.0.0.1:8080/api/v1/academic-period/
content-type: application/json

{
  "initDate": "2024-04-07 12:31:01",
  "endDate": "2024-06-29 12:31:01"
}

### Get current academic period
GET http://127.0.0.1:8080/api/v1/academic-period/current-one/
