### Create a new public info entry, if the user has the role of "CORDINADOR" and the user is active as well
POST http://127.0.0.1:8080/api/v1/lecturer/request-tutor
content-type: application/json

{
  "roleHasPersonIdRolePer": {
      "idRolePer": 1
  },
  "gradeProfileIdGradePro": {
    "idGradePro": 1
  },
  "isAccepted": 0,
  "tutorOrLecturer": 0
}

### GET ALL LECTURES BY PROJECT
GET http://127.0.0.1:8080/api/v1/lecturer/lecturers?idGradeProfile=1

### Upsert Professor to a project
PUT http://127.0.0.1:8080/api/v1/lecturer/assignTutor
content-type: application/json

{
  "roleHasPersonIdRolePer": {
    "idRolePer": 1
  },
  "gradeProfileIdGradePro": {
    "idGradePro": 1
  },
  "isAccepted": 0,
  "tutorOrLecturer": 0,
  "status": 1
}

### GET STUDENTS AND PROFESSORS BY ACTIVE PROJECT WITH DEFAULT PAGINATION
GET http://127.0.0.1:8080/api/v1/lecturer/studentsAndProfessorsByProject
### GET STUDENTS AND PROFESSORS BY ACTIVE PROJECT WHIT PAGINATION
GET http://127.0.0.1:8080/api/v1/lecturer/studentsAndProfessorsByProject?page=0&sort=idTutorApplication
### GET STUDENTS AND PROFESSORS BY ACTIVE PROJECT WITH FILTER
GET http://127.0.0.1:8080/api/v1/lecturer/studentsAndProfessorsByProject?filter=sm&page=0&sort=idTutorApplication
### GET STUDENTS AND PROFESSORS BY ACTIVE PROJECT WITH FILTER
GET http://127.0.0.1:8080/api/v1/lecturer/studentsAndProfessorsByProject?filter=SM&page=0&sort=idTutorApplication
