### Register a new professor with personal data
POST http://127.0.0.1:8080/api/v1/professor/register
Content-Type: application/json

{
  "ci": "3023311",
  "name": "Guile Fabio",
  "fatherLastName": "Gutierrez",
  "motherLastName": "Choquehuanca",
  "description": "Docente de Ingenieria de sistemas y seguridad inteligente",
  "email": "guile.07123@ucb.edu.bo",
  "cellPhone": "0231231"
}

### Obtener todos los docentes con status(1) y rol "DOCENTE"
GET http://127.0.0.1:8080/api/v1/professor/tutores

### Example Request with Pagination
GET http://127.0.0.1:8080/api/v1/professor/tutores?page=0&size=10

### Example Request with Pagination and Sorting
GET http://127.0.0.1:8080/api/v1/professor/tutores?subject=Tecnologias%20Web&page=0&size=10
### sort by email in descending order
GET http://127.0.0.1:8080/api/v1/professor/tutores?page=0&size=10&sort=email,desc
### sort multiple fields
GET http://127.0.0.1:8080/api/v1/professor/tutores?page=0&size=10&sort=name,asc&sort=email,desc

