### Register a new professor with personal data
POST http://127.0.0.1:8080/api/v1/professor/register
Content-Type: application/json

{
  "ci": "3023012",
  "name": "Guile Fabio",
  "fatherLastName": "Gutierrez",
  "motherLastName": "Choquehuanca",
  "description": "Prueba de descripcion",
  "email": "guil2e.070@ucb.edu.bo",
  "cellPhone": "0310321"
}

### Obtener todos los docentes con status(1) y rol "DOCENTE"
GET http://127.0.0.1:8080/api/v1/professor/tutores

### Example Request with Pagination
GET http://127.0.0.1:8080/api/v1/professor/tutores?page=0&size=10

### Example Request with Pagination and Sorting
GET http://127.0.0.1:8080/api/v1/professor/tutores?subject=Tecnologias%20Web&page=0&size=10

### sort by email in descending order
GET http://127.0.0.1:8080/api/v1/professor/tutores?page=0&size=10&sort=email,desc

### sort multiple fields
GET http://127.0.0.1:8080/api/v1/professor/tutores?page=0&size=10&sort=name,asc&sort=email,desc

### Ejemplo FILTRADO con nombres INCOMPLETOS, para busquedas a medias a name, fatherlastname, motherlastname
### (Es decir que acepta cualquiera de los 3 en un solo parametro)
GET http://127.0.0.1:8080/api/v1/professor/tutores?page=0&size=10?sort=createdAt,asc&filter=d

### Obtener detalles de un profesor por ID
GET http://localhost:8080/api/v1/professor/3

Content-Type: application/json

### Reemplaza `1` con el ID del profesor que desees consultar.






