### Register a new professor with personal data
POST http://127.0.0.1:8080/api/v1/professor/register
Content-Type: application/json

{
  "ci": "11233232",
  "name": "Jose Perez",
  "fatherLastName": "Nina",
  "motherLastName": "Reynaga",
  "description": "Docente de Ingenieria de sistemas",
  "email": "carlospro3.nina@ucb.edu.bo",
  "cellPhone": "11111111"
}

### Obtener todos los docentes con status(1) y rol "DOCENTE"
GET http://127.0.0.1:8080/api/v1/professor/all