### Create a new public info entry, if the user has the role of "CORDINADOR" and the user is active as well
POST http://127.0.0.1:8080/api/v1/publicInformation/new
content-type: application/json

{
  "usersIdUsers": {
    "idUsers":1
  },
  "title": "Noticia 2",
  "information": "La noticia de prueba",
  "publicationDate": "2024-04-10 10:31:00",
  "deadline": "2024-04-11 12:31:01"
}

### Get all the actives entries of public information (student)
GET http://127.0.0.1:8080/api/v1/publicInformation/

### Get all the actives entries of public information (coordinator)
GET http://127.0.0.1:8080/api/v1/publicInformation/c

### Get active public information entry by its id
GET http://127.0.0.1:8080/api/v1/publicInformation?idPublicInfo=1

### Logically delete a public information entry
DELETE http://127.0.0.1:8080/api/v1/publicInformation?idPublicInfo=1

### Patching an active entry of public information by its id
PATCH http://127.0.0.1:8080/api/v1/publicInformation/
content-type: application/json

{
  "idPublicInfo": 1,
  "usersIdUsers": {
    "idUsers": 3
  },
  "title": "LA VERDADed",
  "information": "LA NOTICIA NUEVAas",
  "publicationDate": "2024-04-05 12:31:00",
  "deadline": "2024-04-05 12:31:01",
  "status": 1
}


