### Register a new student with personal data and provide PDF Drive URLs
POST http://127.0.0.1:8080/api/v1/student/register
Content-Type: application/json

{
  "ci": "9991233",
  "name": "Carlos Daniel",
  "fatherLastName": "Nina",
  "motherLastName": "Reynaga",
  "description": "Estudiante de 10 semestre",
  "email": "carlospro3.nina@ucb.edu.bo",
  "cellPhone": "12332332",
  "pdfDriveUrls": [
    "http://drive.google.com/99999999",
    "http://drive.google.com/9999999999999999",
    "http://drive.google.com/999999999999999999999999"
  ]
}

### Obtener todos los estudiantes con status_profile 1 en Tabla Drives
GET http://127.0.0.1:8080/api/v1/student/waiting-for-approval

### Obtener todos los estudiantes con status_person = 1
GET http://127.0.0.1:8080/api/v1/student/active-students