### Post new task state
POST http://127.0.0.1:8080/api/v1/task/
content-type: application/json

{
  "titleTask": "TAREA 1",
  "task": "HACER LA TAREA 1",
  "isGradeoneortwo": 1
}

### Get all active tasks ordered by it's id
GET http://127.0.0.1:8080/api/v1/task/

### Get all tasks by its workshop
GET http://127.0.0.1:8080/api/v1/task/work-shop?isGradeoneortwo=1

### Logically delete a task entry
DELETE http://127.0.0.1:8080/api/v1/task?idTask=11

### Patching an active entry of public information by its id
PUT http://127.0.0.1:8080/api/v1/task/
content-type: application/json

{
  "idTask": 1,
  "titleTask": "CAMBIO 31",
  "task": "SE CAMBIO A TAREA 3"


}
