### Post new task state
POST http://127.0.0.1:8080/api/v1/task-date/
content-type: application/json

{
  "taskIdTask": {
    "idTask": 1
  },
  "academicPeriodIdAcad": {
    "idAcad": 1
  },
  "publicationDate": "2024-05-13 12:31:00",
  "deadline": "2024-05-14 12:32:01",
  "orderIs": 1,
  "isUrl": 1,
  "isMeeting": 1
}

### Get all tasks for an academic period ordered by its ordered attribute
GET http://127.0.0.1:8080/api/v1/task-date?idAcad=1&isGradeoneortwo=2

### Post a list of tasks to an academic period with dates
POST http://127.0.0.1:8080/api/v1/task-date/list
content-type: application/json

{
  "tasks": [
    {
      "taskIdTask": {
        "idTask": 1
      },
      "academicPeriodIdAcad": {
        "idAcad": 1
      },
      "publicationDate": "2024-05-13 12:31:00",
      "deadline": "2024-05-14 12:32:01",
      "orderIs": 1,
      "isUrl": 1,
      "isMeeting": 1
    },
    {
      "taskIdTask": {
        "idTask": 1
      },
      "academicPeriodIdAcad": {
        "idAcad": 1
      },
      "publicationDate": "2024-05-13 12:31:00",
      "deadline": "2024-05-14 12:32:01",
      "orderIs": 2,
      "isUrl": 1,
      "isMeeting": 1
    },
    {
      "taskIdTask": {
        "idTask": 1
      },
      "academicPeriodIdAcad": {
        "idAcad": 1
      },
      "publicationDate": "2024-05-13 12:31:00",
      "deadline": "2024-05-14 12:32:01",
      "orderIs": 2,
      "isUrl": 1,
      "isMeeting": 1
    },
    {
      "taskIdTask": {
        "idTask": 1
      },
      "academicPeriodIdAcad": {
        "idAcad": 1
      },
      "publicationDate": "2024-05-13 12:31:00",
      "deadline": "2024-05-14 12:32:01",
      "orderIs": 2,
      "isUrl": 1,
      "isMeeting": 1
    }

  ]
}