### Create a new account for an student
POST http://127.0.0.1:8080/api/v1/users/student
content-type: application/json

{
    "personIdPerson": {
      "idPerson": 14
    }
}

### Create a new account for a professor
POST http://127.0.0.1:8080/api/v1/users/professor
content-type: application/json

{
  "personIdPerson": {
    "idPerson": 9
  }
}

### Create a new account for a coordinator
POST http://127.0.0.1:8080/api/v1/users/coordinator
content-type: application/json

{
  "personIdPerson": {
    "idPerson": 10
  }
}

### Test Log in
POST http://127.0.0.1:8080/api/v1/users/log-in
content-type: application/json

{
  "username": "juan.via@ucb.edu.bo",
  "password": "vcQVxgFjRaVf"
}


### Create a new account for an student
GET http://127.0.0.1:8080/api/v1/users?page=0&size=10?sort=createdAt,asc&filter=fig
content-type: application/json

### Obtener detalles de un usuario por ID
GET http://127.0.0.1:8080/api/v1/users/3
Content-Type: application/json
