### Post new academic period
POST http://127.0.0.1:8080/api/v1/academic-period/
content-type: application/json

{
  "initDate": "2024-01-07 12:31:01",
  "endDate": "2024-06-29 12:31:01",
  "accountUntil": "2024-05-28 12:31:01"
}

### Get all academic periods ordered by dates
GET http://127.0.0.1:8080/api/v1/academic-period/
### Get active academic period by it's ID
GET http://127.0.0.1:8080/api/v1/academic-period?idAcad=24

### Get current academic period
GET http://127.0.0.1:8080/api/v1/academic-period/current-one/

### Delete an active academic period by it's ID
DELETE http://127.0.0.1:8080/api/v1/academic-period?idAcad=1

### Patching an active entry of public information by its id
PUT http://127.0.0.1:8080/api/v1/academic-period/
content-type: application/json

{
  "idAcad" : 24,
  "initDate": "2024-03-08 12:31:01",
  "endDate": "2024-05-30 12:31:01",
  "accountUntil": "2024-04-28 12:31:01"
}
